repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
  - name: redis
    namespace: redis-{{ requiredEnv "ENV" }}
    chart: bitnami/redis
    version: 15.5.4
    values:
      - .infra/helmfiles/{{ requiredEnv "ENV" }}/redis.yaml
    installed: {{ requiredEnv "ENV" | eq "prod" }}

  - name: mysql
    namespace: mysql-{{ requiredEnv "ENV" }}
    chart: bitnami/mysql
    version: 8.8.12
    values:
      - .infra/helmfiles/{{ requiredEnv "ENV" }}/mysql.yaml
    wait: true

  - name: kcd-config
    namespace: kcd-{{ requiredEnv "ENV" }}
    chart: .infra/charts/api  # this is using chart from local directory
    values:
      - .infra/helmfiles/{{ requiredEnv "ENV" }}/config.yaml

  - name: kcd-migration
    namespace: kcd-{{ requiredEnv "ENV" }}
    chart: .infra/charts/api  # this is using chart from local directory
    values:
      - .infra/helmfiles/{{ requiredEnv "ENV" }}/migration.yaml
    needs:
      - kcd-{{ requiredEnv "ENV" }}/redis
      - kcd-{{ requiredEnv "ENV" }}/mysql
      - kcd-{{ requiredEnv "ENV" }}/kcd-config

  - name: kcd-api-server
    namespace: kcd-{{ requiredEnv "ENV" }}
    chart: .infra/charts/api  # this is using chart from local directory
    values:
      - .infra/helmfiles/{{ requiredEnv "ENV" }}/api-server.yaml
    needs:
      - kcd-{{ requiredEnv "ENV" }}/redis
      - kcd-{{ requiredEnv "ENV" }}/mysql
      - kcd-{{ requiredEnv "ENV" }}/kcd-config
      - kcd-{{ requiredEnv "ENV" }}/kcd-migration
