repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
  - name: redis
    namespace: redis-{{ requiredEnv "ENV" }}
    chart: bitnami/redis
    version: 15.5.4
    values:
      - .infra/helmfiles/{{ requiredEnv "ENV" }}/redis.yaml
    installed: {{ requiredEnv "ENV" | eq "prod" }}

  - name: mysql
    namespace: mysql-{{ requiredEnv "ENV" }}
    chart: bitnami/mysql
    version: 8.8.12
    values:
      - .infra/helmfiles/{{ requiredEnv "ENV" }}/mysql.yaml
