auth:
    rootPassword: ENC[AES256_GCM,data:2r8bNpkzVNWkbtr099Lqnw==,iv:XoG61l98LZFT/HFLsyOZ5BcQuoBglEz4/lpd3GkSK0U=,tag:DilzwNhcZIJd1s8JCRfJsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: http://localhost:8200
          engine_path: sops
          key_name: stg
          created_at: "2021-11-06T16:59:11Z"
          enc: vault:v1:lfqVdrH21dn4WFuJnCoMloEHVkewSFeJk2MFUDArV5lJaxBawR7J5urnlqhC+iWXCOQWoMAutZhi8HqH
    age: []
    lastmodified: "2021-11-06T16:59:11Z"
    mac: ENC[AES256_GCM,data:G0rzBiqFDc2EGFVQXF4cpJpgZk5qBqVspNsdY+Q+kNU/tLymqZ/YwIsdaM2KXGWoni9eXsf7Hxj3Hve2fxiP/fsk5VoRLnnL7weAME9Ag4m5pIDjPlYKMT3GICZ2FbOXtPe4IRCQOOvaVCuG2k0TcpY/p2NiHru7yQqlZ2SsOok=,iv:esnAvdnzIiN1T1bitblKellQi3oiqazrOPBAVrY8sdg=,tag:CMaPm6LAG4TG+3WFIIqLHw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
