{{- if .Values.configmap.enabled -}}
{{- $fullname := include "api.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}
data:
  {{- with .Values.configmap.data }}
    {{- toYaml . | nindent 2 }}
  {{- end -}}
{{- end }}
