{{- if .Values.secret.enabled -}}
{{- $fullname := include "api.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
type: {{ .Values.secret.type }}
stringData:
  {{- with .Values.secret.data }}
    {{- toYaml . | nindent 2 }}
  {{- end -}}
{{- end }}
