{{- if .Values.server.enabled -}}
{{- $fullname := include "api.fullname" . -}}apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.port }}
      {{- if eq .Values.server.service.type "NodePort" }}
      nodePort: {{ .Values.server.service.nodePort }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
{{- end }}
